# Generated by Django 4.2.5 on 2024-11-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_id", models.IntegerField()),
                ("folder_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=50)),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("day_streak", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Highscore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.PositiveSmallIntegerField()),
                ("play_time", models.IntegerField()),
                ("score", models.IntegerField()),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="homepage.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="folder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homepage.user"
            ),
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_id", models.IntegerField()),
                ("word", models.CharField(max_length=100)),
                ("meaning", models.CharField(max_length=255)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="homepage.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "folder", "word_id")},
            },
        ),
        migrations.AddConstraint(
            model_name="highscore",
            constraint=models.UniqueConstraint(
                fields=("user", "folder", "game_id", "play_time"),
                name="unique_user_folder_game_play",
            ),
        ),
        migrations.AddConstraint(
            model_name="highscore",
            constraint=models.CheckConstraint(
                check=models.Q(("game_id__in", [1, 2])), name="valid_game_id"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("user", "folder_id")},
        ),
    ]
