# Generated by Django 4.2.5 on 2024-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_check_in",
            field=models.DateField(blank=True, null=True),
        ),
    ]
