# Generated by Django 4.2.5 on 2024-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_user_last_check_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
