# Generated by Django 4.2.5 on 2024-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_user_credits_user_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="card_color",
            field=models.TextField(default="#ffffff"),
        ),
        migrations.AddField(
            model_name="user",
            name="card_color_ava",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="day_streak_left",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="hint_ava",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="title_ava",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
