# Generated by Django 4.2.5 on 2024-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_user_card_color_user_card_color_ava_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="highscore",
            name="valid_game_id",
        ),
        migrations.AddConstraint(
            model_name="highscore",
            constraint=models.CheckConstraint(
                check=models.Q(("game_id__in", [1, 2, 3])), name="valid_game_id"
            ),
        ),
    ]
