# Generated by Django 4.2.5 on 2024-11-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_user_profile_picture"),
        ("homepage", "0005_remove_highscore_valid_game_id_and_more"),
    ]

    operations = []
