# Generated by Django 4.2.5 on 2024-12-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_merge_20241123_1848"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PublicGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("max_players", models.PositiveIntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("FINISHED", "Finished")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="games",
                        through="homepage.GamePlayer",
                        to="homepage.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homepage.publicgame"
            ),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homepage.user"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("game", "user")},
        ),
    ]
