# Generated by Django 4.2.5 on 2024-12-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicgame",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homepage.folder",
            ),
        ),
    ]
