# Generated by Django 4.2.5 on 2024-12-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_publicgame_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicgame",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homepage.folder"
            ),
        ),
    ]
