# Generated by Django 4.2.5 on 2024-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_alter_publicgame_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicgame",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("FLASHCARD", "Flashcard"),
                    ("FLASHCARDCHOICE", "Flashcard Choice"),
                    ("WORDGUESS_EASY", "Wordguess Easy"),
                    ("WORDGUESS_NORMAL", "Wordguess Normal"),
                    ("WORDGUESS_HARD", "Wordguess Hard"),
                ],
                default="FLASHCARD",
                max_length=20,
            ),
        ),
    ]
