# Generated by Django 4.2.5 on 2024-12-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_publicgame_game_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameplayer",
            name="score",
        ),
    ]
