# Generated by Django 4.2.5 on 2024-12-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_publicgame_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicgame",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homepage.user"
            ),
        ),
    ]
