# Generated by Django 5.1.1 on 2024-11-16 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('wordguess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordguessgame',
            name='attempts_left',
        ),
        migrations.RemoveField(
            model_name='wordguessgame',
            name='guesses',
        ),
        migrations.RemoveField(
            model_name='wordguessgame',
            name='incorrect_guesses',
        ),
        migrations.RemoveField(
            model_name='wordguessgame',
            name='word',
        ),
        migrations.AddField(
            model_name='wordguessgame',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordguessgame',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordguessgame',
            name='game_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='wordguessgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.user'),
        ),
    ]
