# Generated by Django 4.2.5 on 2024-12-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wordguess", "0002_remove_wordguessgame_attempts_left_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WordGuessGame",
        ),
    ]
